config/routes.rb
Arenguidee::Application.routes.draw do
  devise_for :users,
    :controllers => {:omniauth_callbacks => "users/sessions"},
    :skip => [:sessions, :registrations]

  devise_scope :user do
    controller "users/sessions" do
      get "/signin"  => :new, :as => :new_user_session
      get "/signout" => :destroy, :as => :destroy_user_session
      get "/users/auth/failure" => :failure if Rails.env.test?
    end
  end

  resources :users, :except => [:new, :create, :destroy] do
    member do
      get :toggle_admin
    end
  end

  resources :categories do
    resources :ideas
  end

  resources :pages
  resources :news, :except => [:show]

  resources :ideas do
    member do
      post :endorse
      post :oppose
    end

    collection do
      get :pending
      get :top
      get :bottom
      get :controversial
    end

    resources :points
  end

  resources :points
  resources :endorsements

  match "/issues" => "issues#index"
  match "/issues.:format" => "issues#index"
  match "/issues/:id" => "issues#show", :as => "issue"
  match "/issues/:id.:format" => "issues#show"
  match "/issues/:id/:action" => "issues#index", :as => :filtered_issue
  match "/issues/:id/:action.:format" => "issues#index"

  root :to => "home#index"
end

app/views/admin/_nav.html.haml
#nav_sub
  %div{:id => "nav_sub_<haml:silent> if ['instances'].include?(params[:controller]) and params[:action] != 'apis' </haml:silent><haml:block>1</haml:block><haml:silent> elsif ['tags'].include?(params[:controller]) </haml:silent><haml:block>2</haml:block><haml:silent> elsif ['picture','picture_save','buddy_icon','buddy_icon_save','fav_icon','fav_icon_save'].include?(params[:action]) </haml:silent><haml:block>4</haml:block><haml:silent> elsif ['color_schemes'].include?(params[:controller]) </haml:silent><haml:block>5</haml:block><haml:silent> elsif ['pages'].include?(params[:controller]) </haml:silent><haml:block>6</haml:block><haml:silent> elsif ['instances'].include?(params[:controller]) and params[:action] == 'apis' </haml:silent><haml:block>9</haml:block>"}
    %ul#menu_sub
      %li.tab1
        %span.tab_header
          = link_to tr("Nation info", "view/admin/_nav"), edit_instance_url(current_instance)
      - if current_instance.is_tags?
        %li.tab2
          %span.tab_header
            = link_to current_instance.tags_name.pluralize.titleize, tags_url
      %li.tab4
        %span.tab_header
          = link_to tr("Graphics", "view/admin/_nav"), :controller => "admin", :action => "picture"
      %li.tab5
        %span.tab_header
          = link_to tr("Colors", "view/admin/_nav"), color_schemes_url
      %li.tab6
        %span.tab_header
          = link_to tr("Pages", "view/admin/_nav"), pages_url
      %li.tab9
        %span.tab_header
          = link_to tr("API keys", "view/admin/_nav"), apis_instance_url(current_instance)
- if ['picture','buddy_icon','fav_icon'].include?(params[:action])
  #nav_third
    %div{:id => "nav_third_<haml:silent> if ['picture'].include?(params[:action]) </haml:silent><haml:block>1</haml:block><haml:silent> elsif ['buddy_icon'].include?(params[:action]) </haml:silent><haml:block>2</haml:block><haml:silent> elsif ['fav_icon'].include?(params[:action]) </haml:silent><haml:block>3</haml:block>"}
      %ul#menu_third
        %li.tab1
          %span.tab_header
            = link_to tr("Logo", "view/admin/_nav"), :controller => "admin", :action => "picture"
        %li.tab2
          %span.tab_header
            = link_to tr("Buddy Icon", "view/admin/_nav"), :controller => "admin", :action => "buddy_icon"
        %li.tab3
          %span.tab_header
            = link_to tr("Fav Icon", "view/admin/_nav"), :controller => "admin", :action => "fav_icon"
- if ['color_schemes'].include?(params[:controller])
  #nav_third
    %div{:id => "nav_third_<haml:silent> if ['index'].include?(params[:action]) </haml:silent><haml:block>1</haml:block><haml:silent> elsif ['new','edit'].include?(params[:action]) </haml:silent><haml:block>2</haml:block>"}
      %ul#menu_third
        %li.tab1
          %span.tab_header
            = link_to tr("Choose a theme", "view/admin/_nav"), color_schemes_url
        %li.tab2
          %span.tab_header
            = link_to tr("Advanced", "view/admin/_nav"), new_color_scheme_path(:id => current_instance.color_scheme)

app/views/admin/all_flagged.html.haml
%b= @page_title
%br/
%br/
- @all.each do |action_item|
  - if action_item.instance_of?(Idea)
    = render :partial => "ideas/flagged_listing", :locals => {:idea => action_item, :suffix => "_noself"}
  - elsif action_item.instance_of?(Point)
    = render :partial => "points/show_full", :locals => {:point => action_item, :revision=>nil, :skip_details=>true, :suffix => "_noself"}
  - elsif action_item.instance_of?(Comment)
    = render :partial => "comments/show", :locals => {:comment => action_item, :suffix => "_noself"}
  _________________________________________________________________
  %br/

app/views/admin/buddy_icon.html.haml
#hp_intro
  = @page_title
%p
  - if current_instance.has_buddy_icon?
    %table{:border => "0", :cellpading => "0", :cellspacing => "0"}
      %tr
        %td= image_tag current_instance.buddy_icon.url(:icon_96), :border => 0
        %td= image_tag current_instance.buddy_icon.url(:icon_48), :border => 0
        %td= image_tag current_instance.buddy_icon.url(:icon_24), :border => 0
  = form_for(current_instance, :url => {:action => "buddy_icon_save" }, :html => {:multipart => true}) do |f|
    = f.error_messages
    %p
      = f.file_field :buddy_icon
      %br/
      %span.small= tr("Must be a gif, jpg or png", "view/admin/buddy_icon")
    %p= submit_tag tr("Upload and save your picture", "view/admin/buddy_icon"), :class => "yellow_button"

app/views/admin/fav_icon.html.haml
#hp_intro
  = @page_title
= tr("The 'fav icon' is the little 16x16 icon in your browser bar. Right now it should look like this:", "view/admin/fav_icon")
%p
  = image_tag current_instance.fav_icon.url(:icon_16), :border => 0
  = form_for(current_instance, :url => {:action => "fav_icon_save" }, :html => {:multipart => true}) do |f|
    = f.error_messages
    = f.file_field :fav_icon
    %br/
    %span.small= tr("Must be a gif, jpg or png", "view/admin/fav_icon")
    %p= submit_tag tr("Upload and save your picture", "view/admin/fav_icon"), :class => "submit_button"

app/views/admin/picture.html.haml
#hp_intro
  = @page_title
%p
  - if current_instance.has_logo?
    = image_tag current_instance.logo.url(:medium), :border => 0
  = form_for(current_instance, :url => {:action => "picture_save" }, :html => {:multipart => true}) do |f|
    = f.error_messages
    = f.file_field :logo
    %br/
    %span.small= tr("Must be a gif, jpg or png", "view/admin/picture")
    %p= submit_tag tr("Upload and save your picture", "view/admin/picture"), :class => "submit_button"