config/routes.rb
Arenguidee::Application.routes.draw do
  devise_for :users,
    :controllers => {:omniauth_callbacks => "users/sessions"},
    :skip => [:sessions, :registrations]

  devise_scope :user do
    controller "users/sessions" do
      get "/signin"  => :new, :as => :new_user_session
      get "/signout" => :destroy, :as => :destroy_user_session
      get "/users/auth/failure" => :failure if Rails.env.test?
    end
  end

  resources :users, :except => [:new, :create, :destroy] do
    member do
      get :toggle_admin
    end
  end

  resources :categories do
    resources :ideas
  end

  resources :pages
  resources :news, :except => [:show]

  resources :ideas do
    member do
      post :endorse
      post :oppose
    end

    collection do
      get :pending
      get :top
      get :bottom
      get :controversial
    end

    resources :points
  end

  resources :points
  resources :endorsements

  match "/issues" => "issues#index"
  match "/issues.:format" => "issues#index"
  match "/issues/:id" => "issues#show", :as => "issue"
  match "/issues/:id.:format" => "issues#show"
  match "/issues/:id/:action" => "issues#index", :as => :filtered_issue
  match "/issues/:id/:action.:format" => "issues#index"

  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!
  
  caches_action :index,
                :if => proc {|c| c.do_action_cache? },
                :cache_path => proc {|c| c.action_cache_path},
                :expires_in => 5.minutes

  caches_action :categories,
                :if => proc {|c| c.do_action_cache? },
                :cache_path => proc {|c| c.action_cache_path},
                :expires_in => 5.minutes

  caches_action :world,
                :if => proc {|c| c.do_action_cache? },
                :cache_path => proc {|c| c.action_cache_path},
                :expires_in => 5.minutes

  caches_action :map,
                :cache_path => proc {|c| c.action_cache_path},
                :expires_in => 15.seconds

  def categories
    @categories = Category.all
    @endorsements = nil
    @ideas = []
    @ideas << @categories.first.ideas.first if @categories and @categories.first and @categories.first.ideas and @categories.first.ideas.first
    if logged_in? # pull all their endorsements on the ideas shown
      all_ideas = []
      @categories.each do |category|
       category.ideas.top_three.each do |idea|
         all_ideas << idea
       end
      end
      @endorsements = current_user.endorsements.active.find(:all, :conditions => ["idea_id in (?)", all_ideas.collect {|c| c.id}])
    end
    last = params[:last].blank? ? Time.now + 1.second : Time.parse(params[:last])
    @activities = Activity.active.top.feed(last).for_all_users.with_20
  end

  def index
    @categories = Category.sorted.all
    @popular = Idea.published.top.limit(15).all(:include => :category)
    @new_ideas = Idea.published.limit(15).order('created_at DESC').all(:include => :category)
    @news = News.order("date DESC").all
    @highlights = Idea.published.random(3)
  end

  def world
    if request.subdomains.any? and request.subdomains[0] != 'www'
      redirect_to "http://www.yrpri.org/home/world"
    else
      @position_in_idea_name = true
      @page_title = tr("{instance_name} Worldwide","shared/language_selection_master",:instance_name => tr(current_instance.name,"Name from database"))
      @ideas = @world_ideas = Idea.unscoped.where(:sub_instance_id=>SubInstance.find_by_short_name("united-nations").id).published.top_rank.limit(3)
      @eu_eea_ideas = Idea.unscoped.where(:sub_instance_id=>SubInstance.find_by_short_name("eu").id).published.top_rank.limit(3)
      @country_sub_instance = SubInstance.where(:iso_country_id=>@iso_country.id).first if @iso_country
      if @country_sub_instance
        @country_sub_instance_ideas = Idea.unscoped.where(:sub_instance_id=>@country_sub_instance.id).published.top_rank.limit(3)
      else
        @country_sub_instance_ideas = []
      end
      #@eu_eea_ideas = @country_sub_instance_ideas = @world_ideas = Idea.published.find(:all, :limit=>3, :order=>"rand()")

      all_ideas = []
      all_ideas += @country_sub_instance_ideas if @country_sub_instance_ideas
      all_ideas += @world_ideas if @world_ideas
      all_ideas += @eu_eea_ideas if @eu_eea_ideas

      @endorsements = nil
      if logged_in? # pull all their endorsements on the ideas shown
        @endorsements = current_user.endorsements.active.find(:all, :conditions => ["idea_id in (?)", all_ideas.collect {|c| c.id}])
      end
    end
  end

  def map
    render :layout=>false, :content_type => 'application/xml'
  end

  def goto
    country = Tr8n::IsoCountry.find_by_country_english_name(params[:country_name])
    sub_instance = SubInstance.find_by_iso_country_id(country.id)
    redirect_to sub_instance.show_url
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def all_countries_in_columns
    one = []
    two = []
    three = []
    four = []
    five = []
    six = []
    flip = 1

    Tr8n::IsoCountry.by_name.all.each do |a|
      if flip==1
        one << a
        flip = 2
      elsif flip==2
        two << a
        flip = 3
      elsif flip==3
        three << a
        flip = 4
      elsif flip==4
        four << a
        flip = 5
      elsif flip==5
        five << a
        flip = 6
      elsif flip==6
        six << a
        flip = 1
      end
    end
    [one,two,three,four,five,six]
  end

  EU_AND_EEA_COUNTRIES = ["at", "be", "bg", "cy", "cz", "dk", "ee", "fi", "fr", "de", "gr", "hu", "ie", "it", "lv", "lt", "lu", "mt", "nl", "pl", "pt", "ro", "sk", "si", "es", "se", "gb","is","no","li","ch"]

  def country_in_eu_or_eea?(country_code)
    EU_AND_EEA_COUNTRIES.include?(country_code.downcase)
  end

  def get_placemark_map_style(country)
    current_sub_instance = SubInstance.current
    SubInstance.current = SubInstance.find_by_iso_country_id(country.id)
    if sub_instance = SubInstance.find_by_iso_country_id(country.id) and Idea.where("sub_instance_id = ?", sub_instance.id).count>0
      ret = "#HasIdeasStyle"
    else
      ret = "#NoIdeaStyle"
    end
    SubInstance.current = SubInstance.current
    ret
  end
end

app/views/home/_country_options.html.haml
- cache(["country_options",locale,SubInstance.current_id,@inline_translations_enabled], :expires_in => 5.seconds) do
  .all_countries
    %table
      %tr
        - all_countries_in_columns.each do |column|
          %td{:align => "center"}
            - column.each do |country|
              - if sub_instance = SubInstance.find_by_iso_country_id(country.id)
                .country
                  = link_to sub_instance.show_url do
                    = image_tag country.medium_flag_image, :size=>"32x32", :border=>0
                    %br
                      = country.country_english_name

app/views/home/_map_element.html.haml
- if country.map_coordinates
  - coordinate_array = JSON.parse(country.map_coordinates)
  :plain
    <Placemark>
          <name>#{country.country_english_name}</name>
          <styleUrl>#{get_placemark_map_style(country)}</styleUrl>
          <description>
          </description>
  - if coordinate_array.length>1
    :plain
      <MultiGeometry>
  - coordinate_array.each do |coordinates|
    = render :partial=>"map_polygon", :locals=>{:coordinates=>coordinates}
  - if coordinate_array.length>1
    :plain
      </MultiGeometry>
  :plain
      </Placemark>

app/views/home/_map_footer.html.haml
:plain
      </Folder>
      </Document>
      </kml>

app/views/home/_map_header.html.haml
:plain
  <?xml version="1.0" encoding="UTF-8"?>
  <kml xmlns="http://www.opengis.net/kml/2.2">
    <Document>
      <Style id="HasIdeaStyle">
        <BalloonStyle>
          <text>$[description]</text>
        </BalloonStyle>
        <PolyStyle>
           <color>550CDDFF</color>
          <colorMode>normal</colorMode>
          <fill>1</fill>
          <outline>0</outline>
        </PolyStyle>
        <LineStyle>
          <color>ff666666</color>
          <colorMode>normal</colorMode>
          <width>0</width>
        </LineStyle>
        <IconStyle>
          <color>FFFFFFFF</color>
          <scale>1.1</scale>
          <hotSpot x="0.5" y="0" xunits="fraction" yunits="fraction"/>
          <Icon>
            <href>http://maps.google.com/mapfiles/kml/paddle/red-blank_maps.png</href>
          </Icon>
        </IconStyle>
      </Style>
      <Style id="NoIdeaStyle">
        <BalloonStyle>
          <text>$[description]</text>
        </BalloonStyle>
        <PolyStyle>
          <color>00666666</color>
          <colorMode>normal</colorMode>
          <fill>1</fill>
          <outline>0</outline>
        </PolyStyle>
        <LineStyle>
          <color>00666666</color>
          <colorMode>normal</colorMode>
          <width>0</width>
        </LineStyle>
        <IconStyle>
          <color>FFFFFFFF</color>
          <scale>1.1</scale>
          <hotSpot x="0.5" y="0" xunits="fraction" yunits="fraction"/>
          <Icon>
            <href>http://maps.google.com/mapfiles/kml/paddle/red-blank_maps.png</href>
          </Icon>
        </IconStyle>
      </Style>
      <Folder id="Fusiontables">

app/views/home/_map_polygon.html.haml
:plain
  <Polygon>
            <outerBoundaryIs>
              <LinearRing>
                <coordinates>
                #{coordinates}
                </coordinates>
              </LinearRing>
            </outerBoundaryIs>
          </Polygon>

app/views/home/categories.html.haml
- if SubInstance.current.message_to_users and SubInstance.current.message_to_users!=""
  = render :partial=>"/shared/top_message_box", :locals=> {:message_text => SubInstance.current.message_to_users.html_safe }
- for category in @categories
  .idea_listing
    %span
      %h4
        = tr("Category:", "model/category") + " "
        %a{:href => "#{category.to_url}"}
          = tr(category.name, "model/category")
          = " (#{category.ideas.count}) -"
        %span.small_text{:style=>""}
          = raw "<a href='/ideas/new?category_id=#{category.id}'>"+tr("Add new idea","model/category")+"</a>"
      - category.ideas.top_three.each do |idea|
        = render :partial=>"ideas/top_level_listing", :locals=>{:idea=>idea, :endorsements=>@endorsements}
- unless @activities.blank?
  %div.home_welcome
    %br
    %h1.home_h1
      = tr("&nbsp;","home")
    %h1
      = tr("Latest Activity","home")
    %ul#endless_scroll_ul.list{:last => @activities.to_a.last.changed_at}
      = render :template => 'feed/activity_list_simple'
      #infinite-scroll
      .endless_scroll_inner_wrap

app/views/home/index.html.haml
%header#home-header
  %h1 Arenguideede konkurss

%section#home-banner
  %a{:href => page_path("about")}
    %img{:src => path_to_image("banner.jpg")}

  %blockquote<
    Mis oleks, kui me oma rahva ja riigina jätaksime ka enda eesmärkidele
    rohkem hulljulget lõtku sisse? Annaks üksteisele ruumi katsetada ja
    ebaõnnestuda, peaasi, et suund on see, milles kokku leppisime?

  .author
    %img{:src => path_to_image("quote-tamkivi.jpg")}
    %strong Sten Tamkivi
    %br
    Hääl mere tagant

  .home-last-year-summary
    %a{:href => 'http://www.arengufond.ee/2014/06/arenguidee-konkursi-2014-loppurituse-salvestused/'}
      %span Eelmise aasta võiduideede kokkuvõte &raquo;


/ #home-new-idea-section
/   %a.button.primary(href=new_idea_path) Esita oma arenguidee

#home-ideas
  %section#home-news
    %h2 Uudised
    %ol
      - @news.each do |news|
        %li
          = link_to_unless(news.url.blank?, news.title, news.url) do
            = news.title
          %strong= news.source
          %time= news.date.strftime("%-d.%2m")
          - unless news.excerpt.blank?
            .excerpt= news.excerpt
  %section#home-categories
    %h2 Teemad
    %ul
      - @categories.each do |category|
        %li.category
          %a{:href => issue_path(category)}
            = category.name
            - if category.ideas.published.count > 0
              %small= category.ideas.published.count
    %h3= link_to 'Kõik ideed', ideas_path

  %section#home-popular-ideas
    %h2 Populaarsemad ideed
    %ol
      - @popular.each do |idea|
        %li
          %a.category{:href => issue_path(idea.category)}= idea.category.name
          %a.idea{:href => idea_path(idea)}
            = idea.name
            - if idea.score > 0
              %small #{idea.score}
  %section#home-new-ideas.new-ideas
    %h2 Uued ideed
    %ol
      - @new_ideas.each do |idea|
        %li
          %a.category{:href => issue_path(idea.category)}= idea.category.name
          %a.idea{:href => idea_path(idea)}
            = idea.name
            - if idea.score > 0
              %small #{idea.score}




  %section#home-outcome
    %a{:href => page_path("about")}
      %p
        Arengufond annab juunis võitjale aastase stipendiumi suurusega 2000
        eurot kuus oma arenguidee teostamiseks.
      %span Loe lähemalt
    %a{:href => 'https://2014.arenguidee.ee'}
      %span Vaata eelmise aasta arenguideede arhiivi &raquo;
%section#home-highlights
  - if !@highlights.empty?
    %ul
      - @highlights.each do |idea|
        %li
          %blockquote= idea.name
          %a{:href => idea_path(idea)}
            %em> Ettepanek
            %span>
              = idea.author.name + ","
              %time= l(idea.published_at.to_date, :format => :long)

    :javascript
      $("#home-highlights ul").cycle({interval: 8000})

  %a.show-all(href=ideas_path)
    Näita kõiki
    = pluralize(Idea.published.count, "ettepanek")

app/views/home/map.html.haml
= render :partial=>"map_header"
- Tr8n::IsoCountry.all.each do |country|
  = render :partial=>"map_element", :locals=>{:country=>country}
= render :partial=>"map_footer"

app/views/home/world.html.haml
%script{:src => "http://maps.googleapis.com/maps/api/js?sensor=false", :type => "text/javascript"}
:javascript
  var kmlLayer = null;
  var map = null;
  var infoWindow = new google.maps.InfoWindow(); // InfoWindow

  function openIW(layerEvt) {
    // infoWindow.setContent(layerEvt.infoWindowHtml);
    // infoWindow.setPosition(layerEvt.latLng);
    if (layerEvt.row) {
      var content = layerEvt.row['admin'].value;
    } else if (layerEvt.featureData) {
      var content = layerEvt.featureData.name;
    }
    window.location = "/home/goto?country_name="+content;
    //document.getElementById('info').innerHTML = "you clicked on:"+content;
  }

  $(document).ready(function() {
      var barcelona = new google.maps.LatLng(41.3719,2.1808);
      var myOptions = {
        zoom: 2,
        center: barcelona,
        mapTypeId: google.maps.MapTypeId.TERRAIN
      }

      map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

      google.maps.event.addListener(map, "click", function() {
        document.getElementById('info').innerHTML = "";
      });

      // 0cddff
      kmlLayer = new google.maps.KmlLayer('http://yrpri.org/home/map?keytime=#{rand(99999999)}', {preserveViewport: true, suppressInfoWindows: true} );
      kmlLayer.setMap(map);

      google.maps.event.addListener(kmlLayer, 'click', openIW);
  });

#map_canvas{:style => "height:300px; width:100%;"}

- if @country_sub_instance_ideas.any?
  %div.home_welcome
    %h1.home_h1
      - sub_instance=SubInstance.find_by_iso_country_id(@iso_country.id)
      = link_to sub_instance.show_url do
        %div.countryflag= image_tag @iso_country.large_flag_image, :border=>0
        %div.country= tr(@iso_country.country_english_name,"welcome")
    - @country_sub_instance_ideas.each do |idea|
      = render :partial=>"ideas/top_level_listing", :locals=>{:idea=>idea, :endorsements=>@endorsements}
      %div
        %div{:id => "idea_detail_#{idea.id}"}
- elsif @iso_country
  - if sub_instance
    = tr("No idea has been created for your country - be the first by clicking here: ","welcome")
    = link_to sub_instance.show_url, sub_instance.show_url

- if @world_ideas.any?
  %div.home_welcome{:style=>"margin-top: 10px; padding-top: 10px;"}
    %h1.home_h1
      - sub_instance=SubInstance.find_by_short_name("united-nations")
      = link_to sub_instance.show_url do
        %div.countryflag= image_tag "tr8n/flags/64/_united-nations.png", :border=>0
        %div.country= tr("United Nations Top Priorities","welcome")
    %h1.home_h1
    - @world_ideas.each do |idea|
      = render :partial=>"ideas/top_level_listing", :locals=>{:idea=>idea, :endorsements=>@endorsements}
      %div
        %div{:id => "idea_detail_#{idea.id}"}
- else
  - if sub_instance
    = tr("No idea has been created for the World - be the first by clicking here: ","welcome")
    = link_to sub_instance.show_url, sub_instance.show_url
- if @eu_eea_ideas.any?
  %br
  %br
  %div.home_welcome
    %h1.home_h1
      - sub_instance=SubInstance.find_by_short_name("eu")
      = link_to sub_instance.show_url do
        %div.countryflag= image_tag "tr8n/flags/64/_european-union.png", :border=>0
        %div.country= tr("European Union and EEA Top Priorities","welcome")
    - @eu_eea_ideas.each do |idea|
      = render :partial=>"ideas/top_level_listing", :locals=>{:idea=>idea, :endorsements=>@endorsements}
      %div
        %div{:id => "idea_detail_#{idea.id}"}
- else
  - if sub_instance
    %div.country= tr("No idea has been created for the European Union and EEA - be the first by clicking here: ","welcome")
    %div.country= link_to sub_instance.show_url, sub_instance.show_url